### ISSUE TITLE
clarification about primary key and foreign key

### ISSUE THREAD

**Issue by ckhung** [ehne/ERDot#8]
The crows foot ER diagram created by ERDot looks really nice :-) I have updated [my script](https://gist.github.com/ckhung/c208ad5b72e7ebe216fd0bfc7fb1cb7a) to generate *.erd.json as input to ERDot and thereby generating a beautiful svg for the sakila sample database. You might consider including the more complex sakila.erd.json as an example input to ERDot.

The comments in README.md about the keys are however somewhat confusing. A [composite key](https://www.javatpoint.com/sql-composite-key) is a primary key composed of two or more fields. It is, however, unrelated to the case of '\*+' prefix to a key. A primary key (\*) which is simultaneously a foreign key (+) is syntactically possible but semantically dubious at best. [The 2nd most voted answer](https://stackoverflow.com/a/8842933) actually makes more sense.

Also, the explanation about the relations and the cardinality indicator need to be fixed. By far the most comon case is:
```ChildTable:ForeignKey1 *--1 ParentTable:PrimaryKey```
In your example.erd.json for example, Person is a child table and BirthPlace is the parent table. The best article I can find by google is [this](https://www.calebcurry.com/parent-child-tables/) but I am sure you can also find the clarification in textbooks, and you can look at the sakila schema for many more examples.

Keep up the good work!

**Comment by ehne** [comment]
Hello,

I'm glad you like the way the diagrams look in ERDot, they're just the nice ones done by Graphviz.

In terms of the keys, we used the term "primary foreign" key to denote the keys in a joining table in my education. Because they are foreign keys that are combined to make a primary key (like a composite key). This is one of the examples:

<img width="464" alt="Screen Shot 2021-04-25 at 9 14 01 am" src="https://user-images.githubusercontent.com/7551957/115975267-97828680-a5a6-11eb-80f6-8d6fc0ca9d60.png">

If there is a better term to describe this type of key, it would be good to know so that I can use the correct language. But as I say, this is just what I was taught, and it is similar to how the `*+` is used in [BurntSushi's one](https://github.com/BurntSushi/erd).

And on the relations explanation, you are correct, the explanation I have there is worded strangely. I think it was supposed to be in reference to the example.erd.json, but something got confused along the way.

thanks,
-ehne

**Comment by ckhung** [comment]
OK, I see your point. To describe this diagram, I would say that roleUser has a composite primary key (user.id, role.id). Each component happens to be also a foreign key. That's indeed a very reasonable situation to have them prefixed with both \* and + at the same time. I admit that it's the first time I hear the term "primary foreign" key. In any case, I would say that your response plus the diagram seem quite worthy of being put to the README.md .

A small fix: ```Person:birthplaceID *--1 BirthPlace:ID``` the last ID should be lower case according to the table definition.
